# Generated by Django 5.1.7 on 2025-06-13 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemedata',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_data', to='schemes.scheme'),
        ),
        migrations.AlterField(
            model_name='schemedata',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_data', to='schemes.state'),
        ),
        migrations.AlterUniqueTogether(
            name='schemedata',
            unique_together={('scheme', 'state', 'year')},
        ),
    ]
